In [1]:
import numpy as np

**Valid Sudoku**

In [2]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

**General Questions**

In [3]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [4]:
#Get the shape of the matrix.
np.shape(data)

(5, 3)

In [5]:
#Find the average age of students.
np.mean(data , axis = 0)[0]

np.float64(18.4)

In [6]:
#Extract Math marks of all students.
data[ : , 1:2]

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [7]:
#Find the highest Science mark.
np.max(data , axis = 1)

array([85, 92, 95, 70, 90])

In [8]:
#Get details of the student who scored more than 90 in Math.
for i in data[ : , 1:2]:
    for j in i:
        if(j>90):
            print(j)

92


In [9]:
#Increase Math marks of all students by 5.
data[ : , 1:2] + 5

array([[90],
       [97],
       [81],
       [70],
       [95]])

In [10]:
#Find how many students are younger than 19.
count = 0
for i in data[ : , 0:1]:
    for j in i:
        if(j>19):
            count += 1
print(count)

1


In [11]:
#Calculate the average marks in each subject (column-wise mean).
marks = np.mean(data , axis=0)
print(f"Average Marks for Maths: {marks[1]}")
print(f"Average Marks for Maths: {marks[2]}")

Average Marks for Maths: 81.6
Average Marks for Maths: 83.2


In [12]:
#Get data of students who scored at least 80 in both subjects.
for i in data[ : , 1:]:
    condition = True
    for j in i:
        if(j<80):
            condition = False
    if(condition == True):
        print(i)

[92 88]
[90 85]


In [15]:
#Replace all Science marks < 75 with 0.
science_marks = data[ : , 2:] 
science_marks.choose(raise choices=0)

SyntaxError: invalid syntax (3324380749.py, line 3)