In [1]:
import numpy as np

Basic Array Creation

In [8]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [11]:
lst = [2, 3.5]
arr2 = np.array(lst)
arr2  #integer is converted to float because arrays can have only one data type

array([2. , 3.5])

In [12]:
lst2 = [2 , 3.5 , "string"]
arr3 = np.array(lst2)
arr3  #Here integera and float both are converted to string

array(['2', '3.5', 'string'], dtype='<U32')

In [13]:
lst2 = [2 , 3.5 , True , False]
arr3 = np.array(lst2)
arr3  #Here integer and Boolean both are converted to Float

array([2. , 3.5, 1. , 0. ])

In [15]:
lst4 = [[1,2,3] , [4,5,6] , [7,8,9]]
# It is a List
print(lst4)
multiDArray = np.array(lst4)
multiDArray 

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation Function

In [16]:
arr5 = np.arange(1, 11 , 2)
arr5

array([1, 3, 5, 7, 9])

In [17]:
arr6 = np.zeros(6) #It will creat a 1-D Array
print(arr6)
print("\n")

arr7 = np.zeros((6,6))  #It will create an array of order 6*6 containing only zeros
print(arr7)

[0. 0. 0. 0. 0. 0.]


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [18]:
arr8 = np.linspace(1,5,3)  
print(arr8)
arr9 = np.linspace(1,5,5)
print(arr9)
arr10 = np.linspace(0 , 1, 10)
print(arr10)


[1. 3. 5.]
[1. 2. 3. 4. 5.]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Random Generation Function

In [19]:
np.random.rand(10)  #It will create 10 elements between 0 and 1

array([0.64885548, 0.7258386 , 0.78593631, 0.840827  , 0.13540787,
       0.32656216, 0.87769988, 0.60011829, 0.14950556, 0.21947658])

In [20]:
np.random.randn(10) #It will create 10 elements between -3 and 3

array([-0.89804779,  0.47783322,  0.37324753, -0.60747744, -0.31239073,
        0.09021053, -0.85722854, -0.00410436,  0.87395724,  1.07217591])

In [21]:
np.random.randint(10) #It will create 1 element between 0 and 10

6

In [22]:
np.random.randint(10 , 20 , 5) #It will create 5 elements between 10 and 20

array([18, 19, 12, 14, 18], dtype=int32)

Array Attributes and Methods

In [23]:
arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr.shape  #It will give the order of Matrix

(3, 3)

In [25]:
arr.size

9

In [26]:
arr.dtype

dtype('int64')

In [27]:
arr.min()

np.int64(1)

In [28]:
arr.max()

np.int64(9)

In [29]:
arr.sum()

np.int64(45)

In [30]:
np.sum(arr , axis = 0) #It will give the sum of Rows

array([12, 15, 18])

In [31]:
np.sum(arr , axis = 1) #It will give the sum of Columns

array([ 6, 15, 24])

In [32]:
arr.mean()

np.float64(5.0)

In [33]:
arr.std()

np.float64(2.581988897471611)

In [34]:
arr.argmax()

np.int64(8)

In [35]:
arr.argmin()

np.int64(0)

Reshaping and Resizing

In [36]:
arr = np.arange(1 , 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [37]:
arr.reshape(6 , 5) #It will not effect the actual array and will only show a changed copy

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [38]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [39]:
arr.resize(6,5)  #It will effect the actual array and will alternate it

In [40]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])